# Generated by Django 3.0.7 on 2020-06-24 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_name', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=220)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Classes')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Professor')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
