# Generated by Django 3.0.7 on 2020-06-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_student_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='professor',
            name='prof_class',
            field=models.ManyToManyField(to='data.Classes'),
        ),
    ]
