# Generated by Django 3.0.7 on 2020-07-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200627_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='prof_class',
            new_name='Classes',
        ),
    ]
